import type { Metadata } from "next";
import { JetBrains_Mono} from "next/font/google";
import "./globals.css";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import CustomCursor from "@/components/customCursor";
import { ToastContainer } from "react-toastify";

const JetBrainsMono = JetBrains_Mono ({
  weight:["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-jetBrainsMono",
});



export const metadata: Metadata = {
  title: "Cyndy-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={JetBrainsMono.variable}>
        <CustomCursor />
        <ToastContainer />
        <StairTransition />
        <PageTransition> {children}</PageTransition>
      </body>
    </html>
  );
}
